name: 'OQuaRE metrics calculation module'
description: 'Calculates the metrics of ontology files in the given folder based on the metrics set by the OQuaRE framework'
inputs:
  ontology-folder:
    description: 'Folder which contains .owl files'
    required: true
    default: 'ontologies'
  contents-folder:
    description: 'Folder which will contain results and archives'
    default: 'OQuaRE'
  reasoner:
    description: 'Reasoner used by OQuaRE'
    required: true
    default: 'ELK'

runs: 
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '8'
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        cache: 'pip'
    - run: pip install -r requirements.txt
      shell: bash

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v18
      with:
        files: |
          ${{ inputs.ontology-folder }}/*.owl
      
    - name: Setup folders
      run: |
        mkdir -p ${{ inputs.contents-folder }} && mkdir -p ${{ inputs.contents-folder }}/results && mkdir -p ${{ inputs.contents-folder }}/archives \
        && mkdir -p ${{ inputs.contents-folder }}/temp_results
      shell: bash
    
    - name: Find and copy previous results
      if: steps.changed-files.outputs.any_changed == 'true'
      run: cp -r $(find ${{ inputs.contents-folder }}/results/* -maxdepth 0)/* ${{ inputs.contents-folder }}/temp_results
      shell: bash

    - name: If file renamed, delete nonmatching folders on temporal folder
      if: steps.changed-files.outputs.renamed_files
      run: |
        comm -13 <(ls -1 ${{ inputs.ontology-folder }} | sed s/.owl//g) <( ls -1 ${{ inputs.contents-folder}}/temp_results) | \
        while read file; do \
          rm -r ${{ inputs.contents-folder}}/temp_results/${file};
        done
      shell: bash

    - name: Checks if its the first run (results empty folder)
      run: |
        if [-z "$(ls -A ${{ inputs.contents-folder }}/results)" ]; then \
          find ./${{ inputs.ontology-folder }} -type f -maxdepth 1 -name "*.owl" | while read file; do \
            outputFile=$(basename "$file" .owl); 
            mkdir -p ${{ inputs.contents-folder }}/temp_results/${outputFile}/metrics; \
            outputFilePath="${{ inputs.contents-folder }}/temp_results/${outputFile}/metrics/${outputFile}.xml"; \
            java -jar libs/oquare-versions.jar --ontology "$file" --reasoner "${{ inputs.reasoner }}" --outputFile "$outputFilePath"; \
            python scripts/main.py -i ${{ inputs.contents-folder }} -c -f "$outputFile"; \
          done

          python scripts/main.py -i ${{ inputs.contents-folder }} -m
        fi
      shell: bash

    - name: Call oquare library
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do \
          outputFile=$(basename "$file" .owl); \
          mkdir -p ${{ inputs.contents-folder }}/temp_results/${outputFile}/metrics; \
          outputFilePath="${{ inputs.contents-folder }}/temp_results/${outputFile}/metrics/${outputFile}.xml"; \
          rm "$outputFilePath"; \
          java -jar libs/oquare-versions.jar --ontology "$file" --reasoner "${{ inputs.reasoner }}" --outputFile "$outputFilePath"; \
          python scripts/main.py -i ${{ inputs.contents-folder }} -c -f "$outputFile"; \
        done
      shell: bash
    
    - name: 'Evaluate and plot oquare model value'
      if: steps.changed-files.outputs.any_changed == 'true'
      run: python scripts/main.py -i ${{ inputs.contents-folder }} -m
      shell: bash
      
    - name: Archive previous results
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        touch ${{ inputs.contents-folder }}/results/temp_file \
        && mv -v ${{ inputs.contents-folder }}/results/* ${{ inputs.contents-folder }}/archives/ \
        && rm -f ${{ inputs.contents-folder }}/archives/temp_file
      shell: bash
    - name: Move results to results folder and tag it with a date
      if: steps.changed-files.outputs.any_changed == 'true'
      run: mv ${{ inputs.contents-folder }}/temp_results ${{ inputs.contents-folder }}/results/"$(date +%d-%m-%Y_%H-%M-%S)"
      shell: bash
    - name: Commit and push
      uses: EndBug/add-and-commit@v8

      
