name: 'OQuaRE metrics calculation module'
description: 'Calculates the metrics of ontology files in the given folder based on the metrics set by the OQuaRE framework'
inputs:
  ontology-folder:
    description: 'Folder which contains .owl files'
    required: true
    default: './ontologies'

runs: 
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
    - run: mkdir -p OQuaRE && mkdir -p OQuaRE/results && mkdir -p OQuaRE/archives
      shell: bash

    - name: Commit and push
      uses: EndBug/add-and-commit@v8